config/routes.rb
Rails.application.routes.draw do
  
  devise_for :eventos
  root 'welcome#index'

  resources :eventos, only: [:index,:show]

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_paramters, if: :devise_controller?
  protected

  def configure_permitted_paramters
  
  	devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:email, :password,
  	 :password_confirmation, :current_password, :title, :description)}

  	devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:email, :password,
  	 :password_confirmation, :current_password, :title, :description)}
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
	def index
		@eventos= Evento.all.order("created_at DESC")
	end
	def show
		@eventos= Evento.find(params[:id])
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/index.html.erb
		<div id="banner" class="eventos_banner">
		<h1>Text goes in here</h1></div>
		<div id="eventos" class="cf">
			<div class="wrapper">
				<ul>
					<% @eventos.each do |evento| %>
					<%= link_to evento do %>
					<li>
							<img src="images/dragon.png" alt="Ninguno">
							<div class="podcast_overview">
								<h2> <%= evento.title %> </h2>
							<p class="episode_count"> persona</p>
							</div>
							
						</li>
					<% end %>
					<% end %>
					
				</ul>	

			</div>
		</div>

app/views/eventos/show.html.erb
<div id="eventos_show">
			<div id="show_banner">
				<div class="wrapper_skinny">
					<h1><%= @eventos.title %></h1>
					<p class="description"> <%= @eventos.description %></p>
					<a href="#" class="suscribe_link">ITunes</a>
					<a href="#" class="suscribe_link">Stitcher</a>
					<a href="#" class="suscribe_link">PodBay</a>	
				</div>
				
			</div>
		
		<div id="breadcrumb">
		<%= link_to eventos_path do %>
		All Podcasts
			<span>/</span>
				The Rocketship Podcast
		<% end %>
			
		</div>
		<div id="episodes">
			<div class="wrapper_skinny">
				<ul class="cf">
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="#">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="personas.html"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

<li class="cf">
						<div class="episode_thumbnail">
							<a href="personas.html">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="personas.html"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

<li class="cf">
						<div class="episode_thumbnail">
							<a href="personas.html">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="personas.html"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

					<li class="cf">
						<div class="episode_thumbnail">
							<a href="personas.html">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="#"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

<li class="cf">
						<div class="episode_thumbnail">
							<a href="personas.html">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="#"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

					<li class="cf">
						<div class="episode_thumbnail">
							<a href="personas.html">
								<img src="images/coca.jpg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><a href="#"></a>How to Pull Off 12 (Well Executed) Startups in 12 Months</h2>
							<p class="description">Pedro Jimenez, founder of Levels.io, talks about how he is building 12 startups in 12 months. Not only do we cover how he is able to pull that off and to will</p>

						</div>
					</li>

				</ul>
			</div>
		</div>

		</div>
<div class="pagination" >
			<span class="previous_page disabled"> Previous </span>
			<em class="current">1</em>
			<a href="#">2</a>
			<a href="next_page" href="#">Next</a>

		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if alert %>

 <p class="alert">
 <%= alert %></p>

 <% elsif notice %>
 	
 

 <p class="notice">
 <%= notice %>
 </p>
 <% end %>

 <header id="main_header"class="cf">
			<div class="wrapper_wide">
			<%= link_to "Por Definir", root_path, id:"logo" %>
			
			<nav>
				<ul>
				<% unless evento_signed_in? %>
					<li><%= link_to "Explore", eventos_path %></li>
					<li>	<%= link_to "Sign In", new_evento_session_path %></li>
					<li><%= link_to "Create an event", new_evento_registration_path  %></li>
				<% else %>
				<li><a href="eventos.html">Dashboard</a></li>
				<li><%= link_to "Explore", eventos_path %>	</li>
				<li><%= link_to "Sign-Out",destroy_evento_session_path, method: :delete %> </li>
				<% end %>
					
				</ul>
			</nav>
		</div>
		</header>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="background">
		<div class="wrapper_wide">
		<header class="cf">
			<a href="index.html" id="logo"> Holaaa</a>
			<nav>
				<ul>
					<% unless evento_signed_in? %>
					<li><a href="eventos.html">Explore</a></li>
					<li>	<%= link_to "Sign In", new_evento_session_path %></li>
					<li><%= link_to "Create an event", new_evento_registration_path  %></li>
				<% else %>
				<li><a href="eventos.html">Dashboard</a></li>
				<li><%= link_to "Explore", eventos_path %>	</li>
				<li><%= link_to "Sign-Out",destroy_evento_session_path, method: :delete %> </li>
				<% end %>
				</ul>
			</nav>
		</div>
		</header>
		<div class="wrapper_skinny">
				<h1>Create a new event <br>, y demas texto.</h1>
				<%= link_to "Create an event", new_evento_registration_path, class:"button button_highlight" %>
			<%= link_to "Explore", eventos_path, class: "button button_white" %>	
				
		</div>
		
	</div>